<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('countries')->insert([
            [
                "id" => 1,
                "name" => "Afghanistan",
                "iso2" => "AF",
                "currency" => "AFN",
            ],
            [
                "id" => 2,
                "name" => "Aland Islands",
                "iso2" => "AX",
                "currency" => "EUR",
            ],
            [
                "id" => 3,
                "name" => "Albania",
                "iso2" => "AL",
                "currency" => "ALL",
            ],
            [
                "id" => 4,
                "name" => "Algeria",
                "iso2" => "DZ",
                "currency" => "DZD",
            ],
            [
                "id" => 5,
                "name" => "American Samoa",
                "iso2" => "AS",
                "currency" => "USD",
            ],
            [
                "id" => 6,
                "name" => "Andorra",
                "iso2" => "AD",
                "currency" => "EUR",
            ],
            [
                "id" => 7,
                "name" => "Angola",
                "iso2" => "AO",
                "currency" => "AOA",
            ],
            [
                "id" => 8,
                "name" => "Anguilla",
                "iso2" => "AI",
                "currency" => "XCD",
            ],
            [
                "id" => 9,
                "name" => "Antarctica",
                "iso2" => "AQ",
                "currency" => "AAD",
            ],
            [
                "id" => 10,
                "name" => "Antigua And Barbuda",
                "iso2" => "AG",
                "currency" => "XCD",
            ],
            [
                "id" => 11,
                "name" => "Argentina",
                "iso2" => "AR",
                "currency" => "ARS",
            ],
            [
                "id" => 12,
                "name" => "Armenia",
                "iso2" => "AM",
                "currency" => "AMD",
            ],
            [
                "id" => 13,
                "name" => "Aruba",
                "iso2" => "AW",
                "currency" => "AWG",
            ],
            [
                "id" => 14,
                "name" => "Australia",
                "iso2" => "AU",
                "currency" => "AUD",
            ],
            [
                "id" => 15,
                "name" => "Austria",
                "iso2" => "AT",
                "currency" => "EUR",
            ],
            [
                "id" => 16,
                "name" => "Azerbaijan",
                "iso2" => "AZ",
                "currency" => "AZN",
            ],
            [
                "id" => 17,
                "name" => "The Bahamas",
                "iso2" => "BS",
                "currency" => "BSD",
            ],
            [
                "id" => 18,
                "name" => "Bahrain",
                "iso2" => "BH",
                "currency" => "BHD",
            ],
            [
                "id" => 19,
                "name" => "Bangladesh",
                "iso2" => "BD",
                "currency" => "BDT",
            ],
            [
                "id" => 20,
                "name" => "Barbados",
                "iso2" => "BB",
                "currency" => "BBD",
            ],
            [
                "id" => 21,
                "name" => "Belarus",
                "iso2" => "BY",
                "currency" => "BYN",
            ],
            [
                "id" => 22,
                "name" => "Belgium",
                "iso2" => "BE",
                "currency" => "EUR",
            ],
            [
                "id" => 23,
                "name" => "Belize",
                "iso2" => "BZ",
                "currency" => "BZD",
            ],
            [
                "id" => 24,
                "name" => "Benin",
                "iso2" => "BJ",
                "currency" => "XOF",
            ],
            [
                "id" => 25,
                "name" => "Bermuda",
                "iso2" => "BM",
                "currency" => "BMD",
            ],
            [
                "id" => 26,
                "name" => "Bhutan",
                "iso2" => "BT",
                "currency" => "BTN",
            ],
            [
                "id" => 27,
                "name" => "Bolivia",
                "iso2" => "BO",
                "currency" => "BOB",
            ],
            [
                "id" => 28,
                "name" => "Bosnia and Herzegovina",
                "iso2" => "BA",
                "currency" => "BAM",
            ],
            [
                "id" => 29,
                "name" => "Botswana",
                "iso2" => "BW",
                "currency" => "BWP",
            ],
            [
                "id" => 30,
                "name" => "Bouvet Island",
                "iso2" => "BV",
                "currency" => "NOK",
            ],
            [
                "id" => 31,
                "name" => "Brazil",
                "iso2" => "BR",
                "currency" => "BRL",
            ],
            [
                "id" => 32,
                "name" => "British Indian Ocean Territory",
                "iso2" => "IO",
                "currency" => "USD",
            ],
            [
                "id" => 33,
                "name" => "Brunei",
                "iso2" => "BN",
                "currency" => "BND",
            ],
            [
                "id" => 34,
                "name" => "Bulgaria",
                "iso2" => "BG",
                "currency" => "BGN",
            ],
            [
                "id" => 35,
                "name" => "Burkina Faso",
                "iso2" => "BF",
                "currency" => "XOF",
            ],
            [
                "id" => 36,
                "name" => "Burundi",
                "iso2" => "BI",
                "currency" => "BIF",
            ],
            [
                "id" => 37,
                "name" => "Cambodia",
                "iso2" => "KH",
                "currency" => "KHR",
            ],
            [
                "id" => 38,
                "name" => "Cameroon",
                "iso2" => "CM",
                "currency" => "XAF",
            ],
            [
                "id" => 39,
                "name" => "Canada",
                "iso2" => "CA",
                "currency" => "CAD",
            ],
            [
                "id" => 40,
                "name" => "Cape Verde",
                "iso2" => "CV",
                "currency" => "CVE",
            ],
            [
                "id" => 41,
                "name" => "Cayman Islands",
                "iso2" => "KY",
                "currency" => "KYD",
            ],
            [
                "id" => 42,
                "name" => "Central African Republic",
                "iso2" => "CF",
                "currency" => "XAF",
            ],
            [
                "id" => 43,
                "name" => "Chad",
                "iso2" => "TD",
                "currency" => "XAF",
            ],
            [
                "id" => 44,
                "name" => "Chile",
                "iso2" => "CL",
                "currency" => "CLP",
            ],
            [
                "id" => 45,
                "name" => "China",
                "iso2" => "CN",
                "currency" => "CNY",
            ],
            [
                "id" => 46,
                "name" => "Christmas Island",
                "iso2" => "CX",
                "currency" => "AUD",
            ],
            [
                "id" => 47,
                "name" => "Cocos (Keeling) Islands",
                "iso2" => "CC",
                "currency" => "AUD",
            ],
            [
                "id" => 48,
                "name" => "Colombia",
                "iso2" => "CO",
                "currency" => "COP",
            ],
            [
                "id" => 49,
                "name" => "Comoros",
                "iso2" => "KM",
                "currency" => "KMF",
            ],
            [
                "id" => 50,
                "name" => "Congo",
                "iso2" => "CG",
                "currency" => "XAF",
            ],
            [
                "id" => 51,
                "name" => "Democratic Republic of the Congo",
                "iso2" => "CD",
                "currency" => "CDF",
            ],
            [
                "id" => 52,
                "name" => "Cook Islands",
                "iso2" => "CK",
                "currency" => "NZD",
            ],
            [
                "id" => 53,
                "name" => "Costa Rica",
                "iso2" => "CR",
                "currency" => "CRC",
            ],
            [
                "id" => 54,
                "name" => "Cote D'Ivoire (Ivory Coast)",
                "iso2" => "CI",
                "currency" => "XOF",
            ],
            [
                "id" => 55,
                "name" => "Croatia",
                "iso2" => "HR",
                "currency" => "HRK",
            ],
            [
                "id" => 56,
                "name" => "Cuba",
                "iso2" => "CU",
                "currency" => "CUP",
            ],
            [
                "id" => 57,
                "name" => "Cyprus",
                "iso2" => "CY",
                "currency" => "EUR",
            ],
            [
                "id" => 58,
                "name" => "Czech Republic",
                "iso2" => "CZ",
                "currency" => "CZK",
            ],
            [
                "id" => 59,
                "name" => "Denmark",
                "iso2" => "DK",
                "currency" => "DKK",
            ],
            [
                "id" => 60,
                "name" => "Djibouti",
                "iso2" => "DJ",
                "currency" => "DJF",
            ],
            [
                "id" => 61,
                "name" => "Dominica",
                "iso2" => "DM",
                "currency" => "XCD",
            ],
            [
                "id" => 62,
                "name" => "Dominican Republic",
                "iso2" => "DO",
                "currency" => "DOP",
            ],
            [
                "id" => 63,
                "name" => "East Timor",
                "iso2" => "TL",
                "currency" => "USD",
            ],
            [
                "id" => 64,
                "name" => "Ecuador",
                "iso2" => "EC",
                "currency" => "USD",
            ],
            [
                "id" => 65,
                "name" => "Egypt",
                "iso2" => "EG",
                "currency" => "EGP",
            ],
            [
                "id" => 66,
                "name" => "El Salvador",
                "iso2" => "SV",
                "currency" => "USD",
            ],
            [
                "id" => 67,
                "name" => "Equatorial Guinea",
                "iso2" => "GQ",
                "currency" => "XAF",
            ],
            [
                "id" => 68,
                "name" => "Eritrea",
                "iso2" => "ER",
                "currency" => "ERN",
            ],
            [
                "id" => 69,
                "name" => "Estonia",
                "iso2" => "EE",
                "currency" => "EUR",
            ],
            [
                "id" => 70,
                "name" => "Ethiopia",
                "iso2" => "ET",
                "currency" => "ETB",
            ],
            [
                "id" => 71,
                "name" => "Falkland Islands",
                "iso2" => "FK",
                "currency" => "FKP",
            ],
            [
                "id" => 72,
                "name" => "Faroe Islands",
                "iso2" => "FO",
                "currency" => "DKK",
            ],
            [
                "id" => 73,
                "name" => "Fiji Islands",
                "iso2" => "FJ",
                "currency" => "FJD",
            ],
            [
                "id" => 74,
                "name" => "Finland",
                "iso2" => "FI",
                "currency" => "EUR",
            ],
            [
                "id" => 75,
                "name" => "France",
                "iso2" => "FR",
                "currency" => "EUR",
            ],
            [
                "id" => 76,
                "name" => "French Guiana",
                "iso2" => "GF",
                "currency" => "EUR",
            ],
            [
                "id" => 77,
                "name" => "French Polynesia",
                "iso2" => "PF",
                "currency" => "XPF",
            ],
            [
                "id" => 78,
                "name" => "French Southern Territories",
                "iso2" => "TF",
                "currency" => "EUR",
            ],
            [
                "id" => 79,
                "name" => "Gabon",
                "iso2" => "GA",
                "currency" => "XAF",
            ],
            [
                "id" => 80,
                "name" => "Gambia The",
                "iso2" => "GM",
                "currency" => "GMD",
            ],
            [
                "id" => 81,
                "name" => "Georgia",
                "iso2" => "GE",
                "currency" => "GEL",
            ],
            [
                "id" => 82,
                "name" => "Germany",
                "iso2" => "DE",
                "currency" => "EUR",
            ],
            [
                "id" => 83,
                "name" => "Ghana",
                "iso2" => "GH",
                "currency" => "GHS",
            ],
            [
                "id" => 84,
                "name" => "Gibraltar",
                "iso2" => "GI",
                "currency" => "GIP",
            ],
            [
                "id" => 85,
                "name" => "Greece",
                "iso2" => "GR",
                "currency" => "EUR",
            ],
            [
                "id" => 86,
                "name" => "Greenland",
                "iso2" => "GL",
                "currency" => "DKK",
            ],
            [
                "id" => 87,
                "name" => "Grenada",
                "iso2" => "GD",
                "currency" => "XCD",
            ],
            [
                "id" => 88,
                "name" => "Guadeloupe",
                "iso2" => "GP",
                "currency" => "EUR",
            ],
            [
                "id" => 89,
                "name" => "Guam",
                "iso2" => "GU",
                "currency" => "USD",
            ],
            [
                "id" => 90,
                "name" => "Guatemala",
                "iso2" => "GT",
                "currency" => "GTQ",
            ],
            [
                "id" => 91,
                "name" => "Guernsey and Alderney",
                "iso2" => "GG",
                "currency" => "GBP",
            ],
            [
                "id" => 92,
                "name" => "Guinea",
                "iso2" => "GN",
                "currency" => "GNF",
            ],
            [
                "id" => 93,
                "name" => "Guinea-Bissau",
                "iso2" => "GW",
                "currency" => "XOF",
            ],
            [
                "id" => 94,
                "name" => "Guyana",
                "iso2" => "GY",
                "currency" => "GYD",
            ],
            [
                "id" => 95,
                "name" => "Haiti",
                "iso2" => "HT",
                "currency" => "HTG",
            ],
            [
                "id" => 96,
                "name" => "Heard Island and McDonald Islands",
                "iso2" => "HM",
                "currency" => "AUD",
            ],
            [
                "id" => 97,
                "name" => "Honduras",
                "iso2" => "HN",
                "currency" => "HNL",
            ],
            [
                "id" => 98,
                "name" => "Hong Kong S.A.R.",
                "iso2" => "HK",
                "currency" => "HKD",
            ],
            [
                "id" => 99,
                "name" => "Hungary",
                "iso2" => "HU",
                "currency" => "HUF",
            ],
            [
                "id" => 100,
                "name" => "Iceland",
                "iso2" => "IS",
                "currency" => "ISK",
            ],
            [
                "id" => 101,
                "name" => "India",
                "iso2" => "IN",
                "currency" => "INR",
            ],
            [
                "id" => 102,
                "name" => "Indonesia",
                "iso2" => "ID",
                "currency" => "IDR",
            ],
            [
                "id" => 103,
                "name" => "Iran",
                "iso2" => "IR",
                "currency" => "IRR",
            ],
            [
                "id" => 104,
                "name" => "Iraq",
                "iso2" => "IQ",
                "currency" => "IQD",
            ],
            [
                "id" => 105,
                "name" => "Ireland",
                "iso2" => "IE",
                "currency" => "EUR",
            ],
            [
                "id" => 106,
                "name" => "Israel",
                "iso2" => "IL",
                "currency" => "ILS",
            ],
            [
                "id" => 107,
                "name" => "Italy",
                "iso2" => "IT",
                "currency" => "EUR",
            ],
            [
                "id" => 108,
                "name" => "Jamaica",
                "iso2" => "JM",
                "currency" => "JMD",
            ],
            [
                "id" => 109,
                "name" => "Japan",
                "iso2" => "JP",
                "currency" => "JPY",
            ],
            [
                "id" => 110,
                "name" => "Jersey",
                "iso2" => "JE",
                "currency" => "GBP",
            ],
            [
                "id" => 111,
                "name" => "Jordan",
                "iso2" => "JO",
                "currency" => "JOD",
            ],
            [
                "id" => 112,
                "name" => "Kazakhstan",
                "iso2" => "KZ",
                "currency" => "KZT",
            ],
            [
                "id" => 113,
                "name" => "Kenya",
                "iso2" => "KE",
                "currency" => "KES",
            ],
            [
                "id" => 114,
                "name" => "Kiribati",
                "iso2" => "KI",
                "currency" => "AUD",
            ],
            [
                "id" => 115,
                "name" => "North Korea",
                "iso2" => "KP",
                "currency" => "KPW",
            ],
            [
                "id" => 116,
                "name" => "South Korea",
                "iso2" => "KR",
                "currency" => "KRW",
            ],
            [
                "id" => 117,
                "name" => "Kuwait",
                "iso2" => "KW",
                "currency" => "KWD",
            ],
            [
                "id" => 118,
                "name" => "Kyrgyzstan",
                "iso2" => "KG",
                "currency" => "KGS",
            ],
            [
                "id" => 119,
                "name" => "Laos",
                "iso2" => "LA",
                "currency" => "LAK",
            ],
            [
                "id" => 120,
                "name" => "Latvia",
                "iso2" => "LV",
                "currency" => "EUR",
            ],
            [
                "id" => 121,
                "name" => "Lebanon",
                "iso2" => "LB",
                "currency" => "LBP",
            ],
            [
                "id" => 122,
                "name" => "Lesotho",
                "iso2" => "LS",
                "currency" => "LSL",
            ],
            [
                "id" => 123,
                "name" => "Liberia",
                "iso2" => "LR",
                "currency" => "LRD",
            ],
            [
                "id" => 124,
                "name" => "Libya",
                "iso2" => "LY",
                "currency" => "LYD",
            ],
            [
                "id" => 125,
                "name" => "Liechtenstein",
                "iso2" => "LI",
                "currency" => "CHF",
            ],
            [
                "id" => 126,
                "name" => "Lithuania",
                "iso2" => "LT",
                "currency" => "EUR",
            ],
            [
                "id" => 127,
                "name" => "Luxembourg",
                "iso2" => "LU",
                "currency" => "EUR",
            ],
            [
                "id" => 128,
                "name" => "Macau S.A.R.",
                "iso2" => "MO",
                "currency" => "MOP",
            ],
            [
                "id" => 129,
                "name" => "North Macedonia",
                "iso2" => "MK",
                "currency" => "MKD",
            ],
            [
                "id" => 130,
                "name" => "Madagascar",
                "iso2" => "MG",
                "currency" => "MGA",
            ],
            [
                "id" => 131,
                "name" => "Malawi",
                "iso2" => "MW",
                "currency" => "MWK",
            ],
            [
                "id" => 132,
                "name" => "Malaysia",
                "iso2" => "MY",
                "currency" => "MYR",
            ],
            [
                "id" => 133,
                "name" => "Maldives",
                "iso2" => "MV",
                "currency" => "MVR",
            ],
            [
                "id" => 134,
                "name" => "Mali",
                "iso2" => "ML",
                "currency" => "XOF",
            ],
            [
                "id" => 135,
                "name" => "Malta",
                "iso2" => "MT",
                "currency" => "EUR",
            ],
            [
                "id" => 136,
                "name" => "Man (Isle of)",
                "iso2" => "IM",
                "currency" => "GBP",
            ],
            [
                "id" => 137,
                "name" => "Marshall Islands",
                "iso2" => "MH",
                "currency" => "USD",
            ],
            [
                "id" => 138,
                "name" => "Martinique",
                "iso2" => "MQ",
                "currency" => "EUR",
            ],
            [
                "id" => 139,
                "name" => "Mauritania",
                "iso2" => "MR",
                "currency" => "MRO",
            ],
            [
                "id" => 140,
                "name" => "Mauritius",
                "iso2" => "MU",
                "currency" => "MUR",
            ],
            [
                "id" => 141,
                "name" => "Mayotte",
                "iso2" => "YT",
                "currency" => "EUR",
            ],
            [
                "id" => 142,
                "name" => "Mexico",
                "iso2" => "MX",
                "currency" => "MXN",
            ],
            [
                "id" => 143,
                "name" => "Micronesia",
                "iso2" => "FM",
                "currency" => "USD",
            ],
            [
                "id" => 144,
                "name" => "Moldova",
                "iso2" => "MD",
                "currency" => "MDL",
            ],
            [
                "id" => 145,
                "name" => "Monaco",
                "iso2" => "MC",
                "currency" => "EUR",
            ],
            [
                "id" => 146,
                "name" => "Mongolia",
                "iso2" => "MN",
                "currency" => "MNT",
            ],
            [
                "id" => 147,
                "name" => "Montenegro",
                "iso2" => "ME",
                "currency" => "EUR",
            ],
            [
                "id" => 148,
                "name" => "Montserrat",
                "iso2" => "MS",
                "currency" => "XCD",
            ],
            [
                "id" => 149,
                "name" => "Morocco",
                "iso2" => "MA",
                "currency" => "MAD",
            ],
            [
                "id" => 150,
                "name" => "Mozambique",
                "iso2" => "MZ",
                "currency" => "MZN",
            ],
            [
                "id" => 151,
                "name" => "Myanmar",
                "iso2" => "MM",
                "currency" => "MMK",
            ],
            [
                "id" => 152,
                "name" => "Namibia",
                "iso2" => "NA",
                "currency" => "NAD",
            ],
            [
                "id" => 153,
                "name" => "Nauru",
                "iso2" => "NR",
                "currency" => "AUD",
            ],
            [
                "id" => 154,
                "name" => "Nepal",
                "iso2" => "NP",
                "currency" => "NPR",
            ],
            [
                "id" => 155,
                "name" => "Bonaire, Sint Eustatius and Saba",
                "iso2" => "BQ",
                "currency" => "USD",
            ],
            [
                "id" => 156,
                "name" => "Netherlands",
                "iso2" => "NL",
                "currency" => "EUR",
            ],
            [
                "id" => 157,
                "name" => "New Caledonia",
                "iso2" => "NC",
                "currency" => "XPF",
            ],
            [
                "id" => 158,
                "name" => "New Zealand",
                "iso2" => "NZ",
                "currency" => "NZD",
            ],
            [
                "id" => 159,
                "name" => "Nicaragua",
                "iso2" => "NI",
                "currency" => "NIO",
            ],
            [
                "id" => 160,
                "name" => "Niger",
                "iso2" => "NE",
                "currency" => "XOF",
            ],
            [
                "id" => 161,
                "name" => "Nigeria",
                "iso2" => "NG",
                "currency" => "NGN",
            ],
            [
                "id" => 162,
                "name" => "Niue",
                "iso2" => "NU",
                "currency" => "NZD",
            ],
            [
                "id" => 163,
                "name" => "Norfolk Island",
                "iso2" => "NF",
                "currency" => "AUD",
            ],
            [
                "id" => 164,
                "name" => "Northern Mariana Islands",
                "iso2" => "MP",
                "currency" => "USD",
            ],
            [
                "id" => 165,
                "name" => "Norway",
                "iso2" => "NO",
                "currency" => "NOK",
            ],
            [
                "id" => 166,
                "name" => "Oman",
                "iso2" => "OM",
                "currency" => "OMR",
            ],
            [
                "id" => 167,
                "name" => "Pakistan",
                "iso2" => "PK",
                "currency" => "PKR",
            ],
            [
                "id" => 168,
                "name" => "Palau",
                "iso2" => "PW",
                "currency" => "USD",
            ],
            [
                "id" => 169,
                "name" => "Palestinian Territory Occupied",
                "iso2" => "PS",
                "currency" => "ILS",
            ],
            [
                "id" => 170,
                "name" => "Panama",
                "iso2" => "PA",
                "currency" => "PAB",
            ],
            [
                "id" => 171,
                "name" => "Papua new Guinea",
                "iso2" => "PG",
                "currency" => "PGK",
            ],
            [
                "id" => 172,
                "name" => "Paraguay",
                "iso2" => "PY",
                "currency" => "PYG",
            ],
            [
                "id" => 173,
                "name" => "Peru",
                "iso2" => "PE",
                "currency" => "PEN",
            ],
            [
                "id" => 174,
                "name" => "Philippines",
                "iso2" => "PH",
                "currency" => "PHP",
            ],
            [
                "id" => 175,
                "name" => "Pitcairn Island",
                "iso2" => "PN",
                "currency" => "NZD",
            ],
            [
                "id" => 176,
                "name" => "Poland",
                "iso2" => "PL",
                "currency" => "PLN",
            ],
            [
                "id" => 177,
                "name" => "Portugal",
                "iso2" => "PT",
                "currency" => "EUR",
            ],
            [
                "id" => 178,
                "name" => "Puerto Rico",
                "iso2" => "PR",
                "currency" => "USD",
            ],
            [
                "id" => 179,
                "name" => "Qatar",
                "iso2" => "QA",
                "currency" => "QAR",
            ],
            [
                "id" => 180,
                "name" => "Reunion",
                "iso2" => "RE",
                "currency" => "EUR",
            ],
            [
                "id" => 181,
                "name" => "Romania",
                "iso2" => "RO",
                "currency" => "RON",
            ],
            [
                "id" => 182,
                "name" => "Russia",
                "iso2" => "RU",
                "currency" => "RUB",
            ],
            [
                "id" => 183,
                "name" => "Rwanda",
                "iso2" => "RW",
                "currency" => "RWF",
            ],
            [
                "id" => 184,
                "name" => "Saint Helena",
                "iso2" => "SH",
                "currency" => "SHP",
            ],
            [
                "id" => 185,
                "name" => "Saint Kitts And Nevis",
                "iso2" => "KN",
                "currency" => "XCD",
            ],
            [
                "id" => 186,
                "name" => "Saint Lucia",
                "iso2" => "LC",
                "currency" => "XCD",
            ],
            [
                "id" => 187,
                "name" => "Saint Pierre and Miquelon",
                "iso2" => "PM",
                "currency" => "EUR",
            ],
            [
                "id" => 188,
                "name" => "Saint Vincent And The Grenadines",
                "iso2" => "VC",
                "currency" => "XCD",
            ],
            [
                "id" => 189,
                "name" => "Saint-Barthelemy",
                "iso2" => "BL",
                "currency" => "EUR",
            ],
            [
                "id" => 190,
                "name" => "Saint-Martin (French part)",
                "iso2" => "MF",
                "currency" => "EUR",
            ],
            [
                "id" => 191,
                "name" => "Samoa",
                "iso2" => "WS",
                "currency" => "WST",
            ],
            [
                "id" => 192,
                "name" => "San Marino",
                "iso2" => "SM",
                "currency" => "EUR",
            ],
            [
                "id" => 193,
                "name" => "Sao Tome and Principe",
                "iso2" => "ST",
                "currency" => "STD",
            ],
            [
                "id" => 194,
                "name" => "Saudi Arabia",
                "iso2" => "SA",
                "currency" => "SAR",
            ],
            [
                "id" => 195,
                "name" => "Senegal",
                "iso2" => "SN",
                "currency" => "XOF",
            ],
            [
                "id" => 196,
                "name" => "Serbia",
                "iso2" => "RS",
                "currency" => "RSD",
            ],
            [
                "id" => 197,
                "name" => "Seychelles",
                "iso2" => "SC",
                "currency" => "SCR",
            ],
            [
                "id" => 198,
                "name" => "Sierra Leone",
                "iso2" => "SL",
                "currency" => "SLL",
            ],
            [
                "id" => 199,
                "name" => "Singapore",
                "iso2" => "SG",
                "currency" => "SGD",
            ],
            [
                "id" => 200,
                "name" => "Slovakia",
                "iso2" => "SK",
                "currency" => "EUR",
            ],
            [
                "id" => 201,
                "name" => "Slovenia",
                "iso2" => "SI",
                "currency" => "EUR",
            ],
            [
                "id" => 202,
                "name" => "Solomon Islands",
                "iso2" => "SB",
                "currency" => "SBD",
            ],
            [
                "id" => 203,
                "name" => "Somalia",
                "iso2" => "SO",
                "currency" => "SOS",
            ],
            [
                "id" => 204,
                "name" => "South Africa",
                "iso2" => "ZA",
                "currency" => "ZAR",
            ],
            [
                "id" => 205,
                "name" => "South Georgia",
                "iso2" => "GS",
                "currency" => "GBP",
            ],
            [
                "id" => 206,
                "name" => "South Sudan",
                "iso2" => "SS",
                "currency" => "SSP",
            ],
            [
                "id" => 207,
                "name" => "Spain",
                "iso2" => "ES",
                "currency" => "EUR",
            ],
            [
                "id" => 208,
                "name" => "Sri Lanka",
                "iso2" => "LK",
                "currency" => "LKR",
            ],
            [
                "id" => 209,
                "name" => "Sudan",
                "iso2" => "SD",
                "currency" => "SDG",
            ],
            [
                "id" => 210,
                "name" => "Suriname",
                "iso2" => "SR",
                "currency" => "SRD",
            ],
            [
                "id" => 211,
                "name" => "Svalbard And Jan Mayen Islands",
                "iso2" => "SJ",
                "currency" => "NOK",
            ],
            [
                "id" => 212,
                "name" => "Swaziland",
                "iso2" => "SZ",
                "currency" => "SZL",
            ],
            [
                "id" => 213,
                "name" => "Sweden",
                "iso2" => "SE",
                "currency" => "SEK",
            ],
            [
                "id" => 214,
                "name" => "Switzerland",
                "iso2" => "CH",
                "currency" => "CHF",
            ],
            [
                "id" => 215,
                "name" => "Syria",
                "iso2" => "SY",
                "currency" => "SYP",
            ],
            [
                "id" => 216,
                "name" => "Taiwan",
                "iso2" => "TW",
                "currency" => "TWD",
            ],
            [
                "id" => 217,
                "name" => "Tajikistan",
                "iso2" => "TJ",
                "currency" => "TJS",
            ],
            [
                "id" => 218,
                "name" => "Tanzania",
                "iso2" => "TZ",
                "currency" => "TZS",
            ],
            [
                "id" => 219,
                "name" => "Thailand",
                "iso2" => "TH",
                "currency" => "THB",
            ],
            [
                "id" => 220,
                "name" => "Togo",
                "iso2" => "TG",
                "currency" => "XOF",
            ],
            [
                "id" => 221,
                "name" => "Tokelau",
                "iso2" => "TK",
                "currency" => "NZD",
            ],
            [
                "id" => 222,
                "name" => "Tonga",
                "iso2" => "TO",
                "currency" => "TOP",
            ],
            [
                "id" => 223,
                "name" => "Trinidad And Tobago",
                "iso2" => "TT",
                "currency" => "TTD",
            ],
            [
                "id" => 224,
                "name" => "Tunisia",
                "iso2" => "TN",
                "currency" => "TND",
            ],
            [
                "id" => 225,
                "name" => "Turkey",
                "iso2" => "TR",
                "currency" => "TRY",
            ],
            [
                "id" => 226,
                "name" => "Turkmenistan",
                "iso2" => "TM",
                "currency" => "TMT",
            ],
            [
                "id" => 227,
                "name" => "Turks And Caicos Islands",
                "iso2" => "TC",
                "currency" => "USD",
            ],
            [
                "id" => 228,
                "name" => "Tuvalu",
                "iso2" => "TV",
                "currency" => "AUD",
            ],
            [
                "id" => 229,
                "name" => "Uganda",
                "iso2" => "UG",
                "currency" => "UGX",
            ],
            [
                "id" => 230,
                "name" => "Ukraine",
                "iso2" => "UA",
                "currency" => "UAH",
            ],
            [
                "id" => 231,
                "name" => "United Arab Emirates",
                "iso2" => "AE",
                "currency" => "AED",
            ],
            [
                "id" => 232,
                "name" => "United Kingdom",
                "iso2" => "GB",
                "currency" => "GBP",
            ],
            [
                "id" => 233,
                "name" => "United States",
                "iso2" => "US",
                "currency" => "USD",
            ],
            [
                "id" => 234,
                "name" => "United States Minor Outlying Islands",
                "iso2" => "UM",
                "currency" => "USD",
            ],
            [
                "id" => 235,
                "name" => "Uruguay",
                "iso2" => "UY",
                "currency" => "UYU",
            ],
            [
                "id" => 236,
                "name" => "Uzbekistan",
                "iso2" => "UZ",
                "currency" => "UZS",
            ],
            [
                "id" => 237,
                "name" => "Vanuatu",
                "iso2" => "VU",
                "currency" => "VUV",
            ],
            [
                "id" => 238,
                "name" => "Vatican City State (Holy See)",
                "iso2" => "VA",
                "currency" => "EUR",
            ],
            [
                "id" => 239,
                "name" => "Venezuela",
                "iso2" => "VE",
                "currency" => "VEF",
            ],
            [
                "id" => 240,
                "name" => "Vietnam",
                "iso2" => "VN",
                "currency" => "VND",
            ],
            [
                "id" => 241,
                "name" => "Virgin Islands (British)",
                "iso2" => "VG",
                "currency" => "USD",
            ],
            [
                "id" => 242,
                "name" => "Virgin Islands (US)",
                "iso2" => "VI",
                "currency" => "USD",
            ],
            [
                "id" => 243,
                "name" => "Wallis And Futuna Islands",
                "iso2" => "WF",
                "currency" => "XPF",
            ],
            [
                "id" => 244,
                "name" => "Western Sahara",
                "iso2" => "EH",
                "currency" => "MAD",
            ],
            [
                "id" => 245,
                "name" => "Yemen",
                "iso2" => "YE",
                "currency" => "YER",
            ],
            [
                "id" => 246,
                "name" => "Zambia",
                "iso2" => "ZM",
                "currency" => "ZMW",
            ],
            [
                "id" => 247,
                "name" => "Zimbabwe",
                "iso2" => "ZW",
                "currency" => "ZWL",
            ],
            [
                "id" => 248,
                "name" => "Kosovo",
                "iso2" => "XK",
                "currency" => "EUR",
            ],
            [
                "id" => 249,
                "name" => "Curaçao",
                "iso2" => "CW",
                "currency" => "ANG",
            ],
            [
                "id" => 250,
                "name" => "Sint Maarten (Dutch part)",
                "iso2" => "SX",
                "currency" => "ANG",
            ]

        ]);
    }
}
